remote_theme: pages-themes/cayman@v0.2.0
plugins: jekyll-remote-theme

title: [Planetary]
description: [This repository contains information on how to build the Open Planetary Chuck for Glass Lathes]
